version: 2.1

orbs:
  ruby: circleci/ruby@2.0.0

jobs:
  run-tests:
    docker:
      - image: cimg/ruby:3.1.3
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rspec-test:
          include: spec/**/*_spec.rb

workflows:
  run-tests-workflow:
    jobs:
      - run-tests
